/**
 * YouTube (youtube.com) handler, search, authentication & subscriptions for Nokia J2ME 240x320
 * MIT License
 */
const { execFile } = require('child_process');
const path = require('path');
const fs = require('fs');

const YT_DLP_PATH = path.join(__dirname, '..', 'tools', 'yt-dlp');
const DATA_DIR = path.join(__dirname, 'data');
const AUTH_FILE = path.join(DATA_DIR, 'youtube_auth.json');
const COOKIES_FILE = path.join(DATA_DIR, 'youtube_cookies.txt');

// Ensure data directory exists
if (!fs.existsSync(DATA_DIR)) {
    try { fs.mkdirSync(DATA_DIR, { recursive: true }); } catch (e) {}
}

// In-memory caches to make repeated queries instantaneous
const searchCache = new Map(); // query -> { timestamp, data }
const videoInfoCache = new Map(); // videoId -> { timestamp, data }
const feedCache = new Map(); // 'feed' -> { timestamp, data }
const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes

const DEMO_CHANNELS = [
    { id: 'UC_n6gOQp_e9yQcE5rV9xLwg', name: 'Nokia', handle: '@nokia' },
    { id: 'UC2wK63A7jA1t7x8iE7P4Y5A', name: 'Action Retro', handle: '@ActionRetro' },
    { id: 'UCLx053rWZxCiYmTHH450GDA', name: 'LGR', handle: '@lazygamer' },
    { id: 'UCQvX28h3_b8_Fq8kSj9W7wA', name: 'Techmoan', handle: '@Techmoan' },
    { id: 'UC8uT9cgJor0Yn5z5b9s5m9w', name: 'The 8-Bit Guy', handle: '@The8BitGuy' }
];

function getAuthState() {
    try {
        if (fs.existsSync(AUTH_FILE)) {
            const raw = fs.readFileSync(AUTH_FILE, 'utf8');
            const parsed = JSON.parse(raw);
            if (hasValidCookies() && !parsed.loggedIn) {
                parsed.loggedIn = true;
                if (!parsed.username) parsed.username = 'YouTube User (Cookie)';
            }
            return parsed;
        }
    } catch (e) {}
    
    // Check if cookies.txt exists standalone
    if (hasValidCookies()) {
        return {
            loggedIn: true,
            username: 'YouTube User (Cookie)',
            isDemo: false,
            subscriptions: [...DEMO_CHANNELS]
        };
    }

    return {
        loggedIn: false,
        username: 'Guest',
        isDemo: false,
        subscriptions: []
    };
}

function saveAuthState(state) {
    try {
        if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
        fs.writeFileSync(AUTH_FILE, JSON.stringify(state, null, 2), 'utf8');
    } catch (e) {
        console.error('[YouTube Auth] Error saving auth state:', e.message);
    }
}

function hasValidCookies() {
    try {
        if (fs.existsSync(COOKIES_FILE)) {
            const stats = fs.statSync(COOKIES_FILE);
            return stats.size > 20;
        }
    } catch (e) {}
    return false;
}

function convertCookieToNetscape(rawCookieStr) {
    if (!rawCookieStr || typeof rawCookieStr !== 'string') return '';
    const trimmed = rawCookieStr.trim();
    if (trimmed.includes('\t') && (trimmed.includes('.youtube.com') || trimmed.includes('youtube.com') || trimmed.includes('# Netscape'))) {
        return trimmed;
    }
    const lines = [
        '# Netscape HTTP Cookie File',
        '# https://curl.se/docs/http-cookies.html',
        '# This file was generated by Nokia Gateway YouTube Auth',
        ''
    ];
    const pairs = trimmed.split(';');
    for (const pair of pairs) {
        const eqIdx = pair.indexOf('=');
        if (eqIdx === -1) continue;
        const key = pair.substring(0, eqIdx).trim();
        const val = pair.substring(eqIdx + 1).trim();
        if (!key) continue;
        lines.push(`.youtube.com\tTRUE\t/\tTRUE\t2147483647\t${key}\t${val}`);
    }
    return lines.join('\n');
}

function saveCookiesFromRaw(raw) {
    const netscape = convertCookieToNetscape(raw);
    if (!netscape) return false;
    try {
        if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
        fs.writeFileSync(COOKIES_FILE, netscape, 'utf8');
        const state = getAuthState();
        state.loggedIn = true;
        state.username = 'YouTube User';
        state.isDemo = false;
        if (!state.subscriptions || state.subscriptions.length === 0) {
            state.subscriptions = [...DEMO_CHANNELS];
        }
        saveAuthState(state);
        feedCache.clear();
        return true;
    } catch (e) {
        console.error('[YouTube Auth] Error saving cookies:', e.message);
        return false;
    }
}

function clearAuth() {
    try {
        if (fs.existsSync(COOKIES_FILE)) fs.unlinkSync(COOKIES_FILE);
    } catch (e) {}
    saveAuthState({
        loggedIn: false,
        username: 'Guest',
        isDemo: false,
        subscriptions: []
    });
    feedCache.clear();
}

function isYouTubeUrl(targetUrl) {
    try {
        const u = new URL(targetUrl);
        const host = u.hostname.toLowerCase();
        return host === 'youtube.com' ||
               host === 'www.youtube.com' ||
               host === 'm.youtube.com' ||
               host === 'youtu.be' ||
               host.endsWith('.youtube.com');
    } catch (e) {
        return false;
    }
}

function extractVideoId(targetUrl) {
    try {
        const u = new URL(targetUrl);
        if (u.hostname === 'youtu.be') {
            const id = u.pathname.substring(1).split(/[?#&]/)[0];
            if (id && id.length === 11 && !id.startsWith('UC')) return id;
        }
        if (u.searchParams.has('v')) {
            const id = u.searchParams.get('v');
            if (id && id.length === 11 && !id.startsWith('UC')) return id;
        }
        const m = u.pathname.match(/\/(?:embed|v|shorts)\/([a-zA-Z0-9_-]{11})(?:[?#&]|$)/);
        if (m) return m[1];
    } catch (e) {}
    const directMatch = targetUrl.match(/[?&]v=([a-zA-Z0-9_-]{11})(?:[&#]|$)/) || targetUrl.match(/youtu\.be\/([a-zA-Z0-9_-]{11})(?:[?#&]|$)/);
    return directMatch ? directMatch[1] : null;
}

function formatDuration(sec) {
    if (!sec || isNaN(sec) || sec <= 0) return '';
    const s = Math.floor(sec);
    const m = Math.floor(s / 60);
    const remS = s % 60;
    const padS = remS < 10 ? '0' + remS : remS;
    if (m < 60) {
        return `${m}:${padS}`;
    }
    const h = Math.floor(m / 60);
    const remM = m % 60;
    const padM = remM < 10 ? '0' + remM : remM;
    return `${h}:${padM}:${padS}`;
}

function formatViews(views) {
    if (!views || isNaN(views)) return '';
    const v = parseInt(views, 10);
    if (v >= 1000000) {
        return (v / 1000000).toFixed(1).replace(/\.0$/, '') + 'M views';
    }
    if (v >= 1000) {
        return (v / 1000).toFixed(1).replace(/\.0$/, '') + 'K views';
    }
    return v + ' views';
}

function runYtDlp(args, timeoutMs = 15000) {
    return new Promise((resolve, reject) => {
        execFile(YT_DLP_PATH, args, { maxBuffer: 10 * 1024 * 1024, timeout: timeoutMs }, (err, stdout, stderr) => {
            if (err) {
                return reject(new Error(stderr || err.message));
            }
            resolve(stdout);
        });
    });
}

async function searchYouTube(query, count = 15) {
    const cleanQ = query.trim();
    const cacheKey = cleanQ.toLowerCase();
    const now = Date.now();

    if (searchCache.has(cacheKey)) {
        const entry = searchCache.get(cacheKey);
        if (now - entry.timestamp < CACHE_TTL_MS) {
            return entry.data;
        }
    }

    try {
        const args = ['--dump-json', `ytsearch${count}:${cleanQ}`, '--flat-playlist', '--no-warnings'];
        if (hasValidCookies()) {
            args.unshift('--cookies', COOKIES_FILE);
        }

        const stdout = await runYtDlp(args, 15000);
        const lines = stdout.trim().split('\n');
        const results = [];
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i].trim();
            if (!line) continue;
            try {
                const item = JSON.parse(line);
                const id = item.id;
                if (!id || id.length !== 11 || id.startsWith('UC') || item._type === 'channel' || item._type === 'playlist') {
                    continue;
                }
                const title = item.title || `Video ${id}`;
                const duration = item.duration_string || formatDuration(item.duration);
                const channel = item.channel || item.uploader || '';
                const views = formatViews(item.view_count);
                let desc = item.description || '';
                if (desc.length > 75) desc = desc.substring(0, 72) + '...';

                let thumb = `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
                if (item.thumbnails && item.thumbnails.length > 0) {
                    thumb = item.thumbnails[0].url;
                }

                results.push({
                    id,
                    title,
                    duration,
                    channel,
                    views,
                    desc,
                    thumb
                });
            } catch (e) {}
        }

        searchCache.set(cacheKey, { timestamp: now, data: results });
        return results;
    } catch (e) {
        console.error('[YouTube Search Error]:', e.message);
        return [];
    }
}

async function getVideoInfo(videoId) {
    const now = Date.now();
    if (videoInfoCache.has(videoId)) {
        const entry = videoInfoCache.get(videoId);
        if (now - entry.timestamp < CACHE_TTL_MS) {
            return entry.data;
        }
    }

    try {
        const args = ['--dump-json', `https://www.youtube.com/watch?v=${videoId}`, '--no-playlist', '--no-warnings'];
        if (hasValidCookies()) {
            args.unshift('--cookies', COOKIES_FILE);
        }
        const stdout = await runYtDlp(args, 15000);

        const data = JSON.parse(stdout.trim());
        const info = {
            id: videoId,
            title: data.title || `YouTube Video ${videoId}`,
            channel: data.channel || data.uploader || 'YouTube Creator',
            views: formatViews(data.view_count),
            duration: data.duration_string || formatDuration(data.duration),
            uploadDate: data.upload_date ? `${data.upload_date.substring(0,4)}-${data.upload_date.substring(4,6)}-${data.upload_date.substring(6,8)}` : '',
            desc: data.description || '',
            thumb: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
        };

        videoInfoCache.set(videoId, { timestamp: now, data: info });
        return info;
    } catch (e) {
        console.error('[YouTube Video Info Error]:', e.message);
        return {
            id: videoId,
            title: `YouTube Video (${videoId})`,
            channel: 'YouTube',
            views: '',
            duration: '',
            uploadDate: '',
            desc: '',
            thumb: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
        };
    }
}

async function getSubscriptionsFeed(count = 15) {
    const auth = getAuthState();
    if (!auth.loggedIn) return [];

    const now = Date.now();
    if (feedCache.has('feed')) {
        const entry = feedCache.get('feed');
        if (now - entry.timestamp < 3 * 60 * 1000) {
            return entry.data;
        }
    }

    let videos = [];

    // Attempt real live subscriptions feed if Netscape cookies exist and not demo
    if (hasValidCookies() && !auth.isDemo) {
        try {
            console.log('[YouTube Auth] Querying live YouTube subscriptions feed...');
            const stdout = await runYtDlp([
                '--cookies', COOKIES_FILE,
                '--dump-json',
                '--flat-playlist',
                '--playlist-end', String(count),
                '--no-warnings',
                'https://www.youtube.com/feed/subscriptions'
            ], 15000);

            const lines = stdout.trim().split('\n');
            for (const line of lines) {
                if (!line.trim()) continue;
                try {
                    const item = JSON.parse(line);
                    const id = item.id;
                    if (!id) continue;
                    videos.push({
                        id,
                        title: item.title || `Video ${id}`,
                        duration: item.duration_string || formatDuration(item.duration),
                        channel: item.channel || item.uploader || 'Creator',
                        views: formatViews(item.view_count),
                        thumb: (item.thumbnails && item.thumbnails.length > 0) ? item.thumbnails[0].url : `https://i.ytimg.com/vi/${id}/hqdefault.jpg`
                    });
                } catch (e) {}
            }
        } catch (err) {
            console.warn('[YouTube Auth] Subscriptions feed query fallback:', err.message);
        }
    }

    // Fallback or Demo mode: Pull recent videos from subscribed channels
    if (videos.length === 0 && auth.subscriptions && auth.subscriptions.length > 0) {
        const channels = auth.subscriptions.slice(0, 5);
        const fetches = channels.map(c => searchYouTube(`${c.name} video`, 3));
        const resLists = await Promise.all(fetches);
        for (const list of resLists) {
            if (Array.isArray(list)) {
                for (const v of list) {
                    if (v && v.id && v.id.length === 11 && !v.id.startsWith('UC')) {
                        videos.push(v);
                    }
                }
            }
        }
        videos = videos.slice(0, count);
    }

    feedCache.set('feed', { timestamp: now, data: videos });
    return videos;
}

async function handleYouTubeRequest(targetUrl, res, gatewayHost, decodeHtmlEntities) {
    try {
        const u = new URL(targetUrl);
        const pathname = u.pathname;
        const videoId = extractVideoId(targetUrl);
        const searchQuery = u.searchParams.get('search_query') || u.searchParams.get('q') || '';
        const isSearch = pathname === '/results' || pathname === '/search' || (u.searchParams.has('search_query'));

        // 1. Account Login / Sign-in Page
        if (pathname === '/login' || pathname === '/signin') {
            return await handleLoginPage(u, res, gatewayHost);
        }

        // 2. Account Logout
        if (pathname === '/logout' || pathname === '/signout') {
            return await handleLogoutPage(res, gatewayHost);
        }

        // 3. Subscriptions Feed (/feed/subscriptions)
        if (pathname === '/feed/subscriptions' || pathname === '/subscriptions') {
            return await handleSubscriptionsPage(res, gatewayHost);
        }

        // 4. Subscribed Channels List (/feed/channels)
        if (pathname === '/feed/channels' || pathname === '/channels') {
            return await handleChannelsPage(res, gatewayHost);
        }

        // 5. In-App Subscribe action
        if (pathname === '/subscribe') {
            const chName = u.searchParams.get('name') || 'Channel';
            const chId = u.searchParams.get('id') || ('ch_' + Date.now());
            const auth = getAuthState();
            if (!auth.subscriptions) auth.subscriptions = [];
            if (!auth.subscriptions.some(c => c.name.toLowerCase() === chName.toLowerCase())) {
                auth.subscriptions.unshift({ id: chId, name: chName });
                saveAuthState(auth);
                feedCache.clear();
            }
            const lines = [
                'META:TITLE=Subscribed to ' + chName,
                'META:URL=https://www.youtube.com/subscribe',
                'META:HTTPS=1',
                'H1:Subscribed!',
                'P:You are now subscribed to ' + chName + '.',
                'L:https://www.youtube.com/feed/subscriptions\t📺 View Subscriptions Feed',
                'L:https://www.youtube.com/feed/channels\t📑 Subscribed Channels (' + auth.subscriptions.length + ')',
                'HR:',
                'L:https://www.youtube.com\t📺 YouTube Home'
            ];
            res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
            return res.end(lines.join('\n'));
        }

        // 6. In-App Unsubscribe action
        if (pathname === '/unsubscribe') {
            const chName = u.searchParams.get('name') || '';
            const auth = getAuthState();
            if (auth.subscriptions) {
                auth.subscriptions = auth.subscriptions.filter(c => c.name.toLowerCase() !== chName.toLowerCase());
                saveAuthState(auth);
                feedCache.clear();
            }
            const lines = [
                'META:TITLE=Unsubscribed',
                'META:URL=https://www.youtube.com/unsubscribe',
                'META:HTTPS=1',
                'H1:Unsubscribed',
                'P:Removed ' + chName + ' from your subscriptions.',
                'L:https://www.youtube.com/feed/channels\t📑 Subscribed Channels (' + (auth.subscriptions ? auth.subscriptions.length : 0) + ')',
                'L:https://www.youtube.com/feed/subscriptions\t📺 View Subscriptions Feed',
                'HR:',
                'L:https://www.youtube.com\t📺 YouTube Home'
            ];
            res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
            return res.end(lines.join('\n'));
        }

        // 7. Watch Page
        if (videoId && (pathname === '/watch' || u.hostname === 'youtu.be' || pathname.startsWith('/shorts/') || pathname.startsWith('/embed/'))) {
            return await handleWatchPage(videoId, targetUrl, res, gatewayHost, decodeHtmlEntities);
        }

        // 8. Search Results Page
        if (isSearch) {
            return await handleSearchPage(searchQuery, targetUrl, res, gatewayHost);
        }

        // 9. YouTube Mobile Homepage
        return await handleHomePage(targetUrl, res, gatewayHost);

    } catch (e) {
        console.error('[YouTube Request Error]:', e.message);
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end(`META:TITLE=YouTube Error\nH1:YouTube Error\nP:${e.message}\nHR:\nL:search:youtube\t🔍 Search YouTube\nL:https://www.youtube.com\t📺 YouTube Home`);
    }
}

async function handleLoginPage(urlObj, res, gatewayHost) {
    // 1. Instant Demo login
    if (urlObj.searchParams.has('demo')) {
        const auth = getAuthState();
        auth.loggedIn = true;
        auth.username = 'RetroTechFan (Demo)';
        auth.isDemo = true;
        auth.subscriptions = [...DEMO_CHANNELS];
        saveAuthState(auth);
        feedCache.clear();

        const lines = [
            'META:TITLE=Signed In (Demo)',
            'META:URL=https://www.youtube.com/login',
            'META:HTTPS=1',
            'H1:Signed In Successfully!',
            'P:Welcome, ' + auth.username + '!',
            'P:Preloaded 5 retro tech channels (Nokia, LGR, Action Retro, Techmoan, 8-Bit Guy).',
            'L:https://www.youtube.com/feed/subscriptions\t📺 View My Subscriptions Feed',
            'L:https://www.youtube.com/feed/channels\t📑 View Subscribed Channels (5)',
            'HR:',
            'L:https://www.youtube.com\t📺 YouTube Home'
        ];
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        return res.end(lines.join('\n'));
    }

    // 2. Cookie submission via phone URL
    if (urlObj.searchParams.has('cookie') || urlObj.searchParams.has('raw_cookie')) {
        const cookieStr = urlObj.searchParams.get('cookie') || urlObj.searchParams.get('raw_cookie');
        const ok = saveCookiesFromRaw(cookieStr);
        const lines = [
            'META:TITLE=Sign In Status',
            'META:URL=https://www.youtube.com/login',
            'META:HTTPS=1'
        ];
        if (ok) {
            lines.push('H1:Signed In Successfully!');
            lines.push('P:Your YouTube session cookies were saved securely.');
            lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 View My Subscriptions');
        } else {
            lines.push('H1:Sign In Failed');
            lines.push('P:Could not parse cookies. Please check format.');
            lines.push('L:https://www.youtube.com/login\tTry Again');
        }
        lines.push('HR:');
        lines.push('L:https://www.youtube.com\t📺 YouTube Home');
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        return res.end(lines.join('\n'));
    }

    const auth = getAuthState();
    const lines = [
        'META:TITLE=YouTube Sign In',
        'META:URL=https://www.youtube.com/login',
        'META:HTTPS=1',
        'H1:Sign In to YouTube'
    ];

    if (auth.loggedIn) {
        lines.push('P:Current Account: ' + auth.username + (auth.isDemo ? ' [Demo]' : ' [Active]'));
        lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 Open Subscriptions Feed');
        lines.push('L:https://www.youtube.com/feed/channels\t📑 Subscribed Channels (' + (auth.subscriptions ? auth.subscriptions.length : 0) + ')');
        lines.push('L:https://www.youtube.com/logout\t🚪 Sign Out');
        lines.push('HR:');
    } else {
        lines.push('P:Sign in to access your YouTube subscriptions, favorite channels, and custom feeds.');
        lines.push('HR:');
        lines.push('H2:Method 1: Instant Demo');
        lines.push('L:https://www.youtube.com/login?demo=1\t⚡ 1-Click Instant Sign In (Demo)');
        lines.push('P:Pre-loads Nokia, LGR, Action Retro & Techmoan for immediate testing.');
        lines.push('HR:');
        lines.push('H2:Method 2: PC/Phone Web Helper');
        lines.push('P:Open this page in any modern browser on Wi-Fi to upload or paste cookies.txt:');
        lines.push('L:http://' + gatewayHost + '/yt_login\t🌐 Open Web Login Helper');
        lines.push('HR:');
        lines.push('H2:Method 3: Paste Cookie on Phone');
        lines.push('L:https://www.youtube.com/login?prompt_cookie=1\t📝 Enter YouTube Session Cookie');
    }

    lines.push('L:https://www.youtube.com\t📺 YouTube Home');

    res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
    return res.end(lines.join('\n'));
}

async function handleLogoutPage(res, gatewayHost) {
    clearAuth();
    const lines = [
        'META:TITLE=YouTube Sign Out',
        'META:URL=https://www.youtube.com/logout',
        'META:HTTPS=1',
        'H1:Signed Out',
        'P:You have been signed out of YouTube.',
        'P:Session cookies and local subscriptions cleared.',
        'HR:',
        'L:https://www.youtube.com/login\t🔑 Sign In Again',
        'L:https://www.youtube.com\t📺 YouTube Home'
    ];
    res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
    return res.end(lines.join('\n'));
}

async function handleSubscriptionsPage(res, gatewayHost) {
    const auth = getAuthState();
    const lines = [];

    lines.push('META:TITLE=YouTube Subscriptions');
    lines.push('META:URL=https://www.youtube.com/feed/subscriptions');
    lines.push('META:HTTPS=1');
    lines.push('H1:My Subscriptions');

    if (!auth.loggedIn) {
        lines.push('P:Sign in to view videos from your subscribed channels.');
        lines.push('L:https://www.youtube.com/login\t🔑 Sign In to YouTube');
        lines.push('L:https://www.youtube.com/login?demo=1\t⚡ Instant Sign In (Demo Account)');
        lines.push('HR:');
        lines.push('L:https://www.youtube.com\t📺 YouTube Home');
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        return res.end(lines.join('\n'));
    }

    const subCount = auth.subscriptions ? auth.subscriptions.length : 0;
    lines.push('P:Account: ' + auth.username + ' • Subscriptions: ' + subCount);
    lines.push('L:https://www.youtube.com/feed/channels\t📑 View Subscribed Channels (' + subCount + ')');
    lines.push('L:https://www.youtube.com/search\t🔍 Search YouTube');
    lines.push('L:https://www.youtube.com/logout\t🚪 Sign Out');
    lines.push('HR:');

    const videos = await getSubscriptionsFeed(15);
    if (videos.length === 0) {
        lines.push('P:No recent videos found from your subscriptions.');
        lines.push('L:https://www.youtube.com/search\t🔍 Search Channels to Subscribe');
    } else {
        for (let i = 0; i < videos.length; i++) {
            const v = videos[i];
            const watchUrl = `https://www.youtube.com/watch?v=${v.id}`;
            const proxyThumb = `http://${gatewayHost}/image?url=${encodeURIComponent(v.thumb)}`;
            const threeGpUrl = `http://${gatewayHost}/video.3gp?url=${encodeURIComponent(watchUrl)}&id=${v.id}`;
            const proxyMedia = `http://${gatewayHost}/media?url=${encodeURIComponent(watchUrl)}`;

            lines.push('H2:' + v.title + (v.duration ? ` [${v.duration}]` : ''));
            lines.push('I:' + proxyThumb + '\t' + v.title);
            lines.push('V:' + threeGpUrl + '\t▶ Stream 3GP (Nokia): ' + v.title);
            lines.push('V:' + proxyMedia + '\t▶ Play Video (Stream): ' + v.title);
            if (v.channel || v.views) {
                lines.push('P:' + (v.channel ? v.channel : '') + (v.views ? ' • ' + v.views : ''));
            }
            lines.push('L:' + watchUrl + '\tDetails & Related');
            lines.push('HR:');
        }
    }

    lines.push('L:https://www.youtube.com/feed/channels\t📑 Manage Subscribed Channels');
    lines.push('L:https://www.youtube.com\t📺 YouTube Home');

    res.writeHead(200, {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*'
    });
    return res.end(lines.join('\n'));
}

async function handleChannelsPage(res, gatewayHost) {
    const auth = getAuthState();
    const lines = [];

    lines.push('META:TITLE=Subscribed Channels');
    lines.push('META:URL=https://www.youtube.com/feed/channels');
    lines.push('META:HTTPS=1');
    lines.push('H1:Subscribed Channels');

    const subs = auth.subscriptions || [];
    lines.push('P:Total Subscriptions: ' + subs.length);
    lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 View Subscriptions Feed');
    lines.push('L:https://www.youtube.com/search\t🔍 Find More Channels');
    lines.push('HR:');

    if (subs.length === 0) {
        lines.push('P:You have not subscribed to any channels yet.');
        lines.push('L:https://www.youtube.com/login?demo=1\t⚡ Load Popular Retro Channels (Demo)');
    } else {
        for (let i = 0; i < subs.length; i++) {
            const ch = subs[i];
            lines.push('H2:' + ch.name + (ch.handle ? ' (' + ch.handle + ')' : ''));
            lines.push('L:https://www.youtube.com/results?search_query=' + encodeURIComponent(ch.name) + '\t📺 Browse Videos: ' + ch.name);
            lines.push('L:https://www.youtube.com/unsubscribe?name=' + encodeURIComponent(ch.name) + '\t➖ Unsubscribe');
            lines.push('HR:');
        }
    }

    lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 Subscriptions Feed');
    lines.push('L:https://www.youtube.com\t📺 YouTube Home');

    res.writeHead(200, {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*'
    });
    return res.end(lines.join('\n'));
}

async function handleWatchPage(videoId, originalUrl, res, gatewayHost, decodeHtmlEntities) {
    const info = await getVideoInfo(videoId);
    const auth = getAuthState();
    const lines = [];

    const cleanTitle = decodeHtmlEntities ? decodeHtmlEntities(info.title) : info.title;
    const cleanDesc = (decodeHtmlEntities ? decodeHtmlEntities(info.desc) : info.desc)
        .replace(/<[^>]+>/g, ' ')
        .replace(/https?:\/\/[^\s]+/g, '')
        .replace(/\s+/g, ' ')
        .trim();

    const proxyThumb = `http://${gatewayHost}/image?url=${encodeURIComponent(info.thumb)}`;
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const threeGpUrl = `http://${gatewayHost}/video.3gp?url=${encodeURIComponent(watchUrl)}&id=${videoId}`;
    const proxyMedia = `http://${gatewayHost}/media?url=${encodeURIComponent(watchUrl)}`;

    lines.push('META:TITLE=' + cleanTitle + ' - YouTube');
    lines.push('META:URL=' + watchUrl);
    lines.push('META:HTTPS=1');
    lines.push('H1:' + cleanTitle);
    lines.push('I:' + proxyThumb + '\t' + cleanTitle);
    lines.push('V:' + threeGpUrl + '\t▶ Play 3GP (Nokia): ' + cleanTitle);
    lines.push('L:' + threeGpUrl + '\t🎬 Launch in Nokia RealPlayer (3GP)');
    lines.push('V:' + proxyMedia + '\t▶ Play Video (Stream): ' + cleanTitle);
    lines.push('A:' + proxyMedia + '\t♫ Audio: ' + cleanTitle);

    let metaLine = 'Channel: ' + info.channel;
    if (info.views) metaLine += ' • ' + info.views;
    if (info.duration) metaLine += ' • ' + info.duration;
    if (info.uploadDate) metaLine += ' • ' + info.uploadDate;
    lines.push('P:' + metaLine);

    // Channel subscription toggle
    const isSubbed = auth.subscriptions && auth.subscriptions.some(c => c.name.toLowerCase() === info.channel.toLowerCase());
    if (isSubbed) {
        lines.push('L:https://www.youtube.com/unsubscribe?name=' + encodeURIComponent(info.channel) + '\t✔️ Subscribed (' + info.channel + ') [Click to Unsubscribe]');
    } else {
        lines.push('L:https://www.youtube.com/subscribe?name=' + encodeURIComponent(info.channel) + '\t➕ Subscribe to ' + info.channel);
    }

    if (cleanDesc) {
        let shortDesc = cleanDesc;
        if (shortDesc.length > 250) {
            shortDesc = shortDesc.substring(0, 245) + '...';
        }
        lines.push('P:' + shortDesc);
    }

    lines.push('HR:');
    lines.push('H2:More on YouTube');
    lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 My Subscriptions');
    lines.push('L:https://www.youtube.com/search\t🔍 Search https://www.youtube.com/');
    lines.push('L:https://www.youtube.com\t📺 YouTube Home');

    res.writeHead(200, {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*'
    });
    return res.end(lines.join('\n'));
}

async function handleSearchPage(query, originalUrl, res, gatewayHost) {
    const lines = [];
    const cleanQ = (query || '').trim();

    lines.push('META:TITLE=' + (cleanQ ? `YouTube: ${cleanQ}` : 'YouTube Search'));
    lines.push('META:URL=' + originalUrl);
    lines.push('META:HTTPS=1');
    lines.push('H1:YouTube Search');

    if (cleanQ) {
        lines.push('P:Results for: "' + cleanQ + '"');
    } else {
        lines.push('P:Search millions of videos on YouTube:');
    }

    lines.push('L:https://www.youtube.com/search\t🔍 Search https://www.youtube.com/ (Click to Type)');
    lines.push('L:search:youtube\t🔍 Quick Search Dialog');
    lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 My Subscriptions');
    lines.push('L:https://www.youtube.com\t📺 Browse YouTube Home');
    lines.push('HR:');

    if (!cleanQ) {
        lines.push('H2:Popular Topics');
        lines.push('L:https://www.youtube.com/results?search_query=Trending\t🔍 Trending Videos');
        lines.push('L:https://www.youtube.com/results?search_query=Music\t🔍 Music');
        lines.push('L:https://www.youtube.com/results?search_query=Gaming\t🔍 Gaming');
        lines.push('L:https://www.youtube.com/results?search_query=Retro+Tech\t🔍 Retro Tech & Phones');
        lines.push('L:https://www.youtube.com/results?search_query=Nokia\t🔍 Nokia Vintage Phones');
        res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
        return res.end(lines.join('\n'));
    }

    const videos = await searchYouTube(cleanQ, 15);

    if (videos.length === 0) {
        lines.push('P:No videos found matching "' + cleanQ + '".');
        lines.push('L:search:youtube\t🔍 Try Another Search');
        lines.push('HR:');
        lines.push('H2:Popular Searches');
        lines.push('L:https://www.youtube.com/results?search_query=Nokia+6300\t🔍 Nokia 6300');
        lines.push('L:https://www.youtube.com/results?search_query=Retro+Computing\t🔍 Retro Computing');
        lines.push('L:https://www.youtube.com/results?search_query=Action+Retro\t🔍 Action Retro');
    } else {
        for (let i = 0; i < videos.length; i++) {
            const v = videos[i];
            const watchUrl = `https://www.youtube.com/watch?v=${v.id}`;
            const proxyThumb = `http://${gatewayHost}/image?url=${encodeURIComponent(v.thumb)}`;
            const threeGpUrl = `http://${gatewayHost}/video.3gp?url=${encodeURIComponent(watchUrl)}&id=${v.id}`;
            const proxyMedia = `http://${gatewayHost}/media?url=${encodeURIComponent(watchUrl)}`;

            lines.push('H2:' + v.title + (v.duration ? ` [${v.duration}]` : ''));
            lines.push('I:' + proxyThumb + '\t' + v.title);
            lines.push('V:' + threeGpUrl + '\t▶ Stream 3GP (Nokia): ' + v.title);
            lines.push('V:' + proxyMedia + '\t▶ Play Video (Stream): ' + v.title);
            if (v.channel || v.views) {
                lines.push('P:' + (v.channel ? v.channel : '') + (v.views ? ' • ' + v.views : ''));
            }
            if (v.desc) {
                lines.push('P:' + v.desc);
            }
            lines.push('L:https://www.youtube.com/watch?v=' + v.id + '\tDetails & Related');
            lines.push('HR:');
        }
        lines.push('L:search:youtube\t🔍 Search YouTube');
        lines.push('L:https://www.youtube.com\t📺 YouTube Home');
    }

    res.writeHead(200, {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*'
    });
    return res.end(lines.join('\n'));
}

async function handleHomePage(originalUrl, res, gatewayHost) {
    const auth = getAuthState();
    const lines = [];

    lines.push('META:TITLE=YouTube Mobile');
    lines.push('META:URL=' + originalUrl);
    lines.push('META:HTTPS=1');
    lines.push('H1:YouTube Mobile');

    // Account header
    if (auth.loggedIn) {
        lines.push('H2:👤 Account: ' + auth.username + (auth.isDemo ? ' [Demo]' : ''));
        lines.push('L:https://www.youtube.com/feed/subscriptions\t📺 My Subscriptions (Feed)');
        lines.push('L:https://www.youtube.com/feed/channels\t📑 Subscribed Channels (' + (auth.subscriptions ? auth.subscriptions.length : 0) + ')');
        lines.push('L:https://www.youtube.com/logout\t🚪 Sign Out');
    } else {
        lines.push('H2:👤 Account: Guest');
        lines.push('L:https://www.youtube.com/login\t🔑 Sign In to YouTube Account');
        lines.push('L:https://www.youtube.com/login?demo=1\t⚡ Instant Sign In (Demo)');
    }
    lines.push('HR:');

    lines.push('L:https://www.youtube.com/search\t🔍 Search https://www.youtube.com/ (Click to Type)');
    lines.push('L:search:youtube\t🔍 Quick Search Dialog');
    lines.push('P:Watch YouTube videos formatted for Nokia 240x320:');

    lines.push('H2:Popular Topics');
    lines.push('L:https://www.youtube.com/results?search_query=Trending\t🔍 Trending Videos');
    lines.push('L:https://www.youtube.com/results?search_query=Music\t🔍 Music');
    lines.push('L:https://www.youtube.com/results?search_query=Gaming\t🔍 Gaming');
    lines.push('L:https://www.youtube.com/results?search_query=Retro+Tech\t🔍 Retro Tech & Phones');
    lines.push('L:https://www.youtube.com/results?search_query=Nokia\t🔍 Nokia Vintage Phones');
    lines.push('HR:');

    lines.push('H2:Featured Videos');
    const videos = await searchYouTube('Trending', 8);
    if (videos.length > 0) {
        for (let i = 0; i < videos.length; i++) {
            const v = videos[i];
            const watchUrl = `https://www.youtube.com/watch?v=${v.id}`;
            const proxyThumb = `http://${gatewayHost}/image?url=${encodeURIComponent(v.thumb)}`;
            const threeGpUrl = `http://${gatewayHost}/video.3gp?url=${encodeURIComponent(watchUrl)}&id=${v.id}`;
            const proxyMedia = `http://${gatewayHost}/media?url=${encodeURIComponent(watchUrl)}`;

            lines.push('H2:' + v.title + (v.duration ? ` [${v.duration}]` : ''));
            lines.push('I:' + proxyThumb + '\t' + v.title);
            lines.push('V:' + threeGpUrl + '\t▶ Stream 3GP (Nokia): ' + v.title);
            lines.push('V:' + proxyMedia + '\t▶ Play Video (Stream): ' + v.title);
            if (v.channel || v.views) {
                lines.push('P:' + (v.channel ? v.channel : '') + (v.views ? ' • ' + v.views : ''));
            }
            lines.push('L:https://www.youtube.com/watch?v=' + v.id + '\tDetails & Related');
            lines.push('HR:');
        }
    }

    lines.push('L:https://www.youtube.com/search\t🔍 Search https://www.youtube.com/');
    lines.push('L:search:youtube\t🔍 Quick Search Dialog');
    lines.push('L:https://www.kamtape.com\t📺 KamTape Retro Videos');
    lines.push('L:https://www.frogfind.com\t🐸 FrogFind Search');

    res.writeHead(200, {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*'
    });
    return res.end(lines.join('\n'));
}

module.exports = {
    isYouTubeUrl,
    extractVideoId,
    searchYouTube,
    getVideoInfo,
    handleYouTubeRequest,
    getAuthState,
    saveAuthState,
    hasValidCookies,
    saveCookiesFromRaw,
    clearAuth,
    DEMO_CHANNELS,
    COOKIES_FILE
};
